# Build-Einstellungen
[build]
  publish = "dist"
  command = "npm run build"


# Umleitungen (optional)
[[redirects]]
  from = "/*"             # Die Quell-URL oder das Muster
  to = "/index.html"      # Das Ziel der Umleitung
  status = 200            # Der HTTP-Statuscode für die Umleitung

