export enum TutorialState {
  INTRODUCTION,
  SELECTING_IMAGE,
  GENERATING_FLASHCARDS,
  DISPLAYING_FLASHCARDS,
  SAVING_FLASHCARDS,
  ADDING_SCHOOL_SUBJECTS,
  REVIEWING_FLASHCARDS,
  EXPLAINING_FLASHCARD_BENEFITS,
  EXPLAINING_OVERVIEW,
  EXPLAINING_COLLECTION,
}

export interface ParentDetails {
  topicTitle: string;
  schoolSubjectTitle: string;
}
